//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManager.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ACCOUNT {
            get {
                return ResourceManager.GetString("ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ADD_NEW_ACCOUNT {
            get {
                return ResourceManager.GetString("ADD_NEW_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Account Details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CHANGE_ACCOUNT_DETAILS {
            get {
                return ResourceManager.GetString("CHANGE_ACCOUNT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COPY_ID {
            get {
                return ResourceManager.GetString("COPY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string COPY_PASSWORD {
            get {
                return ResourceManager.GetString("COPY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DELETE_ACCOUNT {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted accounts cannot be recovered과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DELETE_ACCOUNT_DESC {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Account?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DELETE_ACCOUNT_MSG {
            get {
                return ResourceManager.GetString("DELETE_ACCOUNT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ENTER_PASSWORD_MSG {
            get {
                return ResourceManager.GetString("ENTER_PASSWORD_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Site과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SITE {
            get {
                return ResourceManager.GetString("SITE", resourceCulture);
            }
        }
    }
}
